### ISSUE TITLE
don't autocomplete name

### ISSUE THREAD

**Issue by ToBinio** [JonasPfeifer05/encryptinator-rs-frontend#5]
currently, the name field gets autocompletion from previously created files 

![grafik](https://github.com/JonasPfeifer05/encryptinator-rs-frontend/assets/81473300/3c619b43-1a9f-4413-92bf-3e8801bb4d7c)

this is kinda misleading as file names can't be used multiple times.

**Comment by JonasPfeifer05** [comment]
https://github.com/JonasPfeifer05/encryptinator-rs-frontend/commit/114df01e064bf145376a1b5be0ecf3f77f50932a
