### ISSUE TITLE
click next to button

### ISSUE THREAD

**Issue by ToBinio** [JonasPfeifer05/encryptinator-rs-frontend#6]
In the navbar, you can only click on the text and not on the space surrounding it which is kinda inconvenient

![grafik](https://github.com/JonasPfeifer05/encryptinator-rs-frontend/assets/81473300/c38f6e06-3450-4e95-b636-7a3fe06da87b)

**Comment by JonasPfeifer05** [comment]
https://github.com/JonasPfeifer05/encryptinator-rs-frontend/commit/d2a6a4863772111a00048fb972d03949d82e7fd3
